#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# cobalt-agent installer / updater
# https://github.com/thestark77/cobalt-agent
#
# Single command: curl -fsSL https://raw.githubusercontent.com/thestark77/cobalt-agent/main/install.sh | bash
# Or locally:     bash install.sh
#
# Runs the same whether fresh install or update — always converges to the
# tested configuration without touching private credentials.
# ============================================================================

COBALT_VERSION="0.8.0"
HERMES_REPO="https://github.com/NousResearch/hermes-agent.git"
HERMES_TESTED_TAG=""
HERMES_TESTED_VERSION="0.13.0"
HERMES_MAX_COMPATIBLE="0.13.99"
HERMES_WARN_FROM="0.14.0"
HERMES_ERROR_FROM="1.0.0"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
HERMES_AGENT_DIR="$HERMES_HOME/hermes-agent"
PLUGIN_DIR="$HERMES_HOME/plugins/cobalt-routing"
COBALT_REPO="https://github.com/thestark77/cobalt-agent.git"
COBALT_TMP="/tmp/cobalt-agent-$$"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()   { echo -e "${GREEN}[cobalt]${NC} $*"; }
warn()  { echo -e "${YELLOW}[cobalt]${NC} $*"; }
err()   { echo -e "${RED}[cobalt]${NC} $*" >&2; }
info()  { echo -e "${CYAN}[cobalt]${NC} $*"; }
header(){ echo -e "\n${BLUE}━━━ $* ━━━${NC}\n"; }

cleanup() { rm -rf "$COBALT_TMP" 2>/dev/null || true; }
trap cleanup EXIT

# ── Cron helpers ────────────────────────────────────────────────────────────

CRON_MARKER="# cobalt-routing: patch-verify (managed by install.sh)"
CRON_ENV_FILE="$HOME/.hermes/cobalt-cron.env"

write_cron_env_file() {
    # Persist Telegram + Engram env so the cron job can source them at fire time.
    # File is mode 600 because it can contain tokens.
    mkdir -p "$(dirname "$CRON_ENV_FILE")"
    umask 077
    {
        echo "# Generated by cobalt-agent install.sh — managed file. Re-run install to update."
        [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && echo "export TELEGRAM_BOT_TOKEN=\"${TELEGRAM_BOT_TOKEN}\""
        [ -n "${TELEGRAM_CHAT_ID:-}" ]   && echo "export TELEGRAM_CHAT_ID=\"${TELEGRAM_CHAT_ID}\""
        [ -n "${ENGRAM_CLOUD_SERVER:-}" ] && echo "export ENGRAM_CLOUD_SERVER=\"${ENGRAM_CLOUD_SERVER}\""
        [ -n "${ENGRAM_CLOUD_TOKEN:-}" ]  && echo "export ENGRAM_CLOUD_TOKEN=\"${ENGRAM_CLOUD_TOKEN}\""
        [ -n "${ENGRAM_CLOUD_AUTOSYNC:-}" ] && echo "export ENGRAM_CLOUD_AUTOSYNC=\"${ENGRAM_CLOUD_AUTOSYNC}\""
    } > "$CRON_ENV_FILE"
    chmod 600 "$CRON_ENV_FILE"
}

build_cron_entry() {
    # Daily 09:00 local — runs the verifier through the env file.
    local verify_script="$1"
    echo "0 9 * * * . $CRON_ENV_FILE && /usr/bin/env bash $verify_script >> $HOME/.hermes/cobalt-cron.log 2>&1 $CRON_MARKER"
}

setup_verify_cron() {
    if [ "${COBALT_INSTALL_CRON:-1}" = "0" ]; then
        log "COBALT_INSTALL_CRON=0 — skipping cron setup"
        return 0
    fi

    if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
        warn "TELEGRAM_BOT_TOKEN/TELEGRAM_CHAT_ID not set — patch-verify cron skipped"
        warn "Export both and re-run installer to enable VPS-side patch monitoring."
        return 0
    fi

    if ! command -v crontab &>/dev/null; then
        warn "crontab not found — patch-verify cron skipped (install cron and re-run)"
        return 0
    fi

    local verify_script="$HOME/.hermes/cobalt-verify-patch.sh"
    cp "$COBALT_TMP/scripts/verify-patch.sh" "$verify_script"
    chmod +x "$verify_script"

    write_cron_env_file
    local new_entry
    new_entry=$(build_cron_entry "$verify_script")

    # Idempotent crontab edit: strip any prior cobalt entry, append new one.
    local existing
    existing=$(crontab -l 2>/dev/null || true)
    local without_old
    without_old=$(echo "$existing" | grep -v -F "$CRON_MARKER" || true)

    if [ "$without_old" = "$existing" ] && echo "$existing" | grep -qF "$CRON_MARKER"; then
        # nothing to strip
        :
    fi

    local desired
    if [ -n "$without_old" ]; then
        desired=$(printf "%s\n%s\n" "$without_old" "$new_entry")
    else
        desired="$new_entry"
    fi

    # Compare with current crontab — only update if changed
    if [ "$existing" = "$desired" ]; then
        log "Cron job already up to date (daily 09:00)"
        return 0
    fi

    echo "$desired" | crontab -
    if echo "$existing" | grep -qF "$CRON_MARKER"; then
        log "Cron job updated (daily 09:00 — Telegram notifications)"
    else
        log "Cron job installed (daily 09:00 — Telegram notifications)"
    fi
}

_install_engram_binary() {
    # Auto-installer for the Engram CLI/MCP binary.
    # Pulls the latest official release tarball, extracts to ~/.local/bin/engram,
    # and verifies the resulting binary runs. Idempotent + safe to re-run.
    local arch os asset url tmp_dir
    case "$(uname -s)" in
        Linux)  os="linux"   ;;
        Darwin) os="darwin"  ;;
        *)
            warn "Unsupported OS '$(uname -s)' for auto-install. Install engram manually."
            return 1
            ;;
    esac
    case "$(uname -m)" in
        x86_64|amd64) arch="amd64" ;;
        aarch64|arm64) arch="arm64" ;;
        *)
            warn "Unsupported arch '$(uname -m)' for auto-install. Install engram manually."
            return 1
            ;;
    esac

    log "Resolving latest Engram release..."
    local release_json tag tarball
    release_json=$(curl -fsSL https://api.github.com/repos/Gentleman-Programming/engram/releases/latest 2>/dev/null || true)
    if [ -z "$release_json" ]; then
        warn "Could not fetch Engram release metadata (network?). Skipping auto-install."
        return 1
    fi

    tag=$(echo "$release_json" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tag_name',''))" 2>/dev/null)
    if [ -z "$tag" ]; then
        warn "Could not parse Engram release tag. Skipping auto-install."
        return 1
    fi

    # Tarball name pattern: engram_<version>_<os>_<arch>.tar.gz  (version w/o the 'v')
    local version="${tag#v}"
    tarball="engram_${version}_${os}_${arch}.tar.gz"
    url="https://github.com/Gentleman-Programming/engram/releases/download/${tag}/${tarball}"

    tmp_dir=$(mktemp -d) || return 1
    log "Downloading Engram ${tag} (${os}/${arch})..."
    if ! curl -fsSL "$url" -o "$tmp_dir/$tarball"; then
        warn "Engram download failed from $url"
        rm -rf "$tmp_dir"
        return 1
    fi

    tar -xzf "$tmp_dir/$tarball" -C "$tmp_dir" 2>/dev/null || {
        warn "Engram tarball extraction failed"
        rm -rf "$tmp_dir"
        return 1
    }

    local extracted_bin
    extracted_bin=$(find "$tmp_dir" -maxdepth 2 -name engram -type f -executable 2>/dev/null | head -n1)
    if [ -z "$extracted_bin" ]; then
        warn "engram binary not found inside the tarball"
        rm -rf "$tmp_dir"
        return 1
    fi

    mkdir -p "$HOME/.local/bin"
    mv "$extracted_bin" "$HOME/.local/bin/engram"
    chmod +x "$HOME/.local/bin/engram"
    rm -rf "$tmp_dir"

    if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
        if ! grep -q '\.local/bin' "$HOME/.bashrc" 2>/dev/null; then
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
        fi
        export PATH="$HOME/.local/bin:$PATH"
    fi
    hash -r 2>/dev/null || true

    if "$HOME/.local/bin/engram" --version &>/dev/null; then
        log "Engram installed: $("$HOME/.local/bin/engram" --version 2>&1 | head -n1)"
        return 0
    else
        warn "Engram binary installed at ~/.local/bin/engram but failed --version check"
        return 1
    fi
}

check_engram_binary() {
    # Soft-detect first (PATH miss is common right after installing to ~/.local/bin)
    if command -v engram &>/dev/null; then
        log "engram binary found: $(command -v engram)"
        return 0
    fi
    if [ -x "$HOME/.local/bin/engram" ]; then
        export PATH="$HOME/.local/bin:$PATH"
        hash -r 2>/dev/null || true
        log "engram binary found: $HOME/.local/bin/engram (added ~/.local/bin to PATH)"
        return 0
    fi

    # Only auto-install when the user actually wants Engram (env vars present);
    # otherwise we'd download a binary nobody asked for.
    if [ "${ENGRAM_ENABLED:-0}" != "1" ]; then
        warn "engram binary not in PATH and ENGRAM_CLOUD_SERVER/TOKEN not set."
        warn "Export them and re-run installer to enable memory."
        return 1
    fi

    log "engram binary missing but Engram Cloud env vars set — auto-installing..."
    if _install_engram_binary; then
        return 0
    fi
    warn "Engram auto-install failed. Memory MCP will be inactive."
    warn "Install manually: https://github.com/Gentleman-Programming/engram (Homebrew or download from Releases)."
    return 1
}

# ── Helpers ─────────────────────────────────────────────────────────────────

version_tuple() {
    local v="$1"
    local major minor patch
    major=$(echo "$v" | cut -d. -f1)
    minor=$(echo "$v" | cut -d. -f2)
    patch=$(echo "$v" | cut -d. -f3)
    printf "%03d%03d%03d" "${major:-0}" "${minor:-0}" "${patch:-0}"
}

version_gte() { [ "$(version_tuple "$1")" -ge "$(version_tuple "$2")" ]; }
version_gt()  { [ "$(version_tuple "$1")" -gt "$(version_tuple "$2")" ]; }

read_hermes_version() {
    local pyproject="$HERMES_AGENT_DIR/pyproject.toml"
    if [ -f "$pyproject" ]; then
        python3 -c "
import tomllib, sys
with open('$pyproject', 'rb') as f:
    data = tomllib.load(f)
print(data.get('project', {}).get('version', '0.0.0'))
" 2>/dev/null || echo "0.0.0"
    else
        echo "0.0.0"
    fi
}

check_hermes_compat() {
    local ver="$1"
    if version_gte "$ver" "$HERMES_ERROR_FROM"; then
        err "Hermes $ver is INCOMPATIBLE with cobalt-routing v${COBALT_VERSION}"
        err "cobalt-routing was tested on Hermes $HERMES_TESTED_VERSION"
        err "Hermes >= $HERMES_ERROR_FROM introduces breaking changes."
        err "Wait for a cobalt-agent update or pin Hermes to a compatible version."
        exit 1
    fi
    if version_gte "$ver" "$HERMES_WARN_FROM"; then
        warn "Hermes $ver is ABOVE the tested version ($HERMES_TESTED_VERSION)"
        warn "cobalt-routing may still work, but has not been validated on this version."
        warn "Proceeding anyway — report issues at https://github.com/thestark77/cobalt-agent/issues"
        echo ""
    fi
}

# ── Detect install vs update ────────────────────────────────────────────────

IS_UPDATE=0
if [ -f "$HERMES_AGENT_DIR/pyproject.toml" ] && [ -f "$PLUGIN_DIR/__init__.py" ]; then
    IS_UPDATE=1
fi

# ============================================================================
header "cobalt-agent v${COBALT_VERSION} — $([ "$IS_UPDATE" -eq 1 ] && echo 'Updater' || echo 'Installer')"
# ============================================================================

if [ "$IS_UPDATE" -eq 1 ]; then
    CURRENT_VER=$(read_hermes_version)
    log "Existing installation detected (Hermes $CURRENT_VER)"
    log "Mode: UPDATE — will upgrade components to tested versions"
    echo ""
    echo "This updater will:"
    echo "  1. Check prerequisites"
    echo "  2. Update Hermes Agent to latest tested version"
    echo "  3. Update OpenCode Go provider"
    echo "  4. Re-apply source patch (safe if already applied)"
    echo "  5. Update cobalt-routing plugin to v${COBALT_VERSION}"
    echo "  6. Update SOUL.md + merge config (preserves your settings) + Engram MCP"
    echo "  7. Update skills"
    echo "  8. Patch verify automation (cron + Telegram alerts)"
    echo "  9. Verify everything"
else
    echo "This installer will set up:"
    echo "  1. Prerequisites check"
    echo "  2. Hermes Agent (latest tested version)"
    echo "  3. OpenCode Go provider (free model access)"
    echo "  4. Source patch (delegate_tool.py routing hook)"
    echo "  5. cobalt-routing plugin (routing + tool guard + skills + memory protocol)"
    echo "  6. SOUL.md + configuration + Engram MCP server"
    echo "  7. Skills (15 curated skills)"
    echo "  8. Patch verify automation (cron + Telegram alerts)"
    echo "  9. Verification"
fi
echo ""
echo "Required env vars (set before running):"
echo "  ENGRAM_CLOUD_SERVER, ENGRAM_CLOUD_TOKEN  — Engram Cloud memory backend"
echo ""
echo "Optional env vars:"
echo "  ENGRAM_CLOUD_AUTOSYNC                    — auto-sync local Engram to cloud"
echo "  TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID     — patch-drift alerts via cron"
echo "  COBALT_INSTALL_CRON=0                    — skip cron job installation"
echo ""

# ============================================================================
header "Step 1/9: Prerequisites"
# ============================================================================

check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        err "$1 not found. Please install it first."
        return 1
    fi
    log "$1 found: $(command -v "$1")"
}

MISSING=0
check_cmd git || MISSING=1
check_cmd python3 || MISSING=1
check_cmd curl || MISSING=1
check_cmd pip3 || check_cmd pip || MISSING=1

PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PYTHON_MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 11 ]); then
    err "Python 3.11+ required (found $PYTHON_VERSION)"
    MISSING=1
fi

if ! python3 -c "import venv" 2>/dev/null; then
    err "python3-venv not found. Install it: sudo apt install python${PYTHON_VERSION}-venv"
    MISSING=1
else
    log "python3-venv module available"
fi

if [ "$MISSING" -eq 1 ]; then
    err "Missing prerequisites. Install them and re-run."
    exit 1
fi

log "Python $PYTHON_VERSION OK"

HAS_NPM=0
if command -v npm &>/dev/null || command -v npx &>/dev/null; then
    HAS_NPM=1
    log "npm found"
else
    warn "npm not found. OpenCode CLI won't be installed (you can configure provider manually)"
fi

# ============================================================================
header "Step 2/9: Hermes Agent"
# ============================================================================

VENV_DIR="$HERMES_AGENT_DIR/venv"

if [ -f "$HERMES_AGENT_DIR/pyproject.toml" ]; then
    CURRENT_VER=$(read_hermes_version)
    log "Hermes Agent found at $HERMES_AGENT_DIR (v$CURRENT_VER)"

    check_hermes_compat "$CURRENT_VER"

    if [ "$IS_UPDATE" -eq 1 ]; then
        log "Updating Hermes Agent..."
        cd "$HERMES_AGENT_DIR"
        git fetch origin 2>/dev/null || warn "Could not fetch updates (network issue?)"

        if [ -n "$HERMES_TESTED_TAG" ]; then
            git checkout "$HERMES_TESTED_TAG" 2>/dev/null || {
                warn "Tag $HERMES_TESTED_TAG not found, staying on current version"
            }
        else
            git pull origin main 2>/dev/null || warn "Could not pull updates"
        fi
        cd - >/dev/null

        NEW_VER=$(read_hermes_version)
        if [ "$CURRENT_VER" != "$NEW_VER" ]; then
            log "Updated: $CURRENT_VER → $NEW_VER"
            check_hermes_compat "$NEW_VER"
        else
            log "Already at latest compatible version ($CURRENT_VER)"
        fi
    fi
else
    log "Installing Hermes Agent..."
    mkdir -p "$HERMES_HOME"
    if [ -n "$HERMES_TESTED_TAG" ]; then
        git clone --depth 1 --branch "$HERMES_TESTED_TAG" "$HERMES_REPO" "$HERMES_AGENT_DIR"
    else
        git clone --depth 1 "$HERMES_REPO" "$HERMES_AGENT_DIR"
    fi
    log "Hermes Agent cloned"

    FRESH_VER=$(read_hermes_version)
    check_hermes_compat "$FRESH_VER"
fi

if [ ! -f "$VENV_DIR/bin/pip" ]; then
    log "Creating Python virtual environment..."
    rm -rf "$VENV_DIR"
    python3 -m venv "$VENV_DIR"
fi

log "Installing Hermes dependencies..."
"$VENV_DIR/bin/pip" install -q --upgrade pip
"$VENV_DIR/bin/pip" install -q -e "$HERMES_AGENT_DIR"

# markitdown-mcp (Microsoft official) — converts files (PDF/DOCX/XLSX/audio/...)
# to Markdown so sub-agents don't burn tokens on binary content. Pulled from
# PyPI (auto-updates on every install.sh run).
log "Installing markitdown-mcp..."
if "$VENV_DIR/bin/pip" install -q --upgrade markitdown-mcp 2>/dev/null; then
    log "markitdown-mcp installed/updated"
    MARKITDOWN_BIN="$VENV_DIR/bin/markitdown-mcp"
    if [ ! -x "$MARKITDOWN_BIN" ]; then
        warn "markitdown-mcp binary not found at $MARKITDOWN_BIN after install"
        MARKITDOWN_BIN=""
    fi
else
    warn "markitdown-mcp install failed (continuing without it)"
    MARKITDOWN_BIN=""
fi

mkdir -p "$HOME/.local/bin"
ln -sf "$VENV_DIR/bin/hermes" "$HOME/.local/bin/hermes"
log "Linked hermes -> ~/.local/bin/hermes"

if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
    export PATH="$HOME/.local/bin:$PATH"
    log "Added ~/.local/bin to PATH"
fi

FINAL_VER=$(read_hermes_version)
log "Hermes Agent v$FINAL_VER ready"

# ============================================================================
header "Step 3/9: OpenCode Go Provider"
# ============================================================================

if [ "$HAS_NPM" -eq 1 ]; then
    if ! command -v opencode &>/dev/null; then
        log "Installing OpenCode CLI (opencode-ai on npm)..."
        # Correct npm package is `opencode-ai` (binary: `opencode`).
        # Older fallbacks left for backwards compat with mis-named registries.
        if npm install -g opencode-ai 2>/dev/null \
            || npm install -g opencode 2>/dev/null \
            || npm install -g @sst-software/opencode 2>/dev/null; then
            if command -v opencode &>/dev/null; then
                log "OpenCode CLI installed ($(command -v opencode))"
            else
                warn "OpenCode CLI install reported success but 'opencode' not in PATH."
                warn "Check 'npm root -g' and ensure that dir is in your PATH."
            fi
        else
            warn "OpenCode CLI install failed. You'll need to configure the provider manually."
            warn "Set model.base_url in ~/.hermes/config.yaml to your provider's endpoint."
        fi
    else
        log "OpenCode CLI already installed ($(command -v opencode))"
    fi
fi

log "Provider will be configured in Step 6"

# ============================================================================
header "Step 4/9: Source Patch (delegate_tool.py)"
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

if [ -d "$SCRIPT_DIR/src" ] && [ -f "$SCRIPT_DIR/src/__init__.py" ]; then
    COBALT_TMP="$SCRIPT_DIR"
    log "Using local source files ($SCRIPT_DIR)"
else
    log "Fetching cobalt-agent source from GitHub..."
    if [ -d "$COBALT_TMP" ]; then
        rm -rf "$COBALT_TMP"
    fi
    git clone --depth 1 "$COBALT_REPO" "$COBALT_TMP" 2>/dev/null || {
        err "Cannot fetch cobalt-agent source and no local files found"
        exit 1
    }
fi

PATCH_SCRIPT="$COBALT_TMP/patches/apply_routing_patch.py"
if [ -f "$PATCH_SCRIPT" ]; then
    PATCH_STATUS=$("$VENV_DIR/bin/python" "$PATCH_SCRIPT" verify 2>&1 || true)
    if echo "$PATCH_STATUS" | grep -qi "applied\|verified\|true"; then
        log "Source patch already applied (idempotent check passed)"
        log "Re-applying to ensure latest version..."
    fi
    "$VENV_DIR/bin/python" "$PATCH_SCRIPT" apply || {
        warn "Patch apply returned non-zero — checking if already applied..."
        if "$VENV_DIR/bin/python" "$PATCH_SCRIPT" verify 2>/dev/null; then
            log "Patch verified OK (was already applied)"
        else
            warn "Patch could not be applied or verified (routing will use inference fallback)"
        fi
    }
else
    warn "Patch script not found, skipping (routing will use inference only)"
fi

# ============================================================================
header "Step 5/9: cobalt-routing Plugin"
# ============================================================================

if [ "$IS_UPDATE" -eq 1 ] && [ -f "$PLUGIN_DIR/__init__.py" ]; then
    OLD_PLUGIN_VER=$(python3 -c "
import re
text = open('$PLUGIN_DIR/__init__.py').read()
m = re.search(r'PLUGIN_VERSION\s*=\s*\"(.*?)\"', text)
print(m.group(1) if m else 'unknown')
" 2>/dev/null || echo "unknown")
    log "Updating plugin: v$OLD_PLUGIN_VER -> v$COBALT_VERSION"
fi

mkdir -p "$PLUGIN_DIR"

PLUGIN_FILES=(
    "__init__.py"
    "router.py"
    "tool_guard.py"
    "skill_injector.py"
    "sdd_triage.py"
    "version_manager.py"
    "compat.py"
    "preset_tool.py"
    "plugin.yaml"
    "presets.yaml"
)

COPIED=0
for f in "${PLUGIN_FILES[@]}"; do
    if [ -f "$COBALT_TMP/src/$f" ]; then
        cp "$COBALT_TMP/src/$f" "$PLUGIN_DIR/$f"
        COPIED=$((COPIED + 1))
    fi
done

log "Plugin installed at $PLUGIN_DIR ($COPIED files)"

# ============================================================================
header "Step 6/9: SOUL.md + Configuration"
# ============================================================================

if [ -f "$COBALT_TMP/SOUL.md" ]; then
    cp "$COBALT_TMP/SOUL.md" "$HERMES_HOME/SOUL.md"
    log "SOUL.md deployed"
else
    warn "SOUL.md not found in source, skipping"
fi

CONFIG_FILE="$HERMES_HOME/config.yaml"

# Detect Engram env vars (the only thing the user needs to set)
ENGRAM_SERVER="${ENGRAM_CLOUD_SERVER:-}"
ENGRAM_TOKEN="${ENGRAM_CLOUD_TOKEN:-}"
ENGRAM_AUTOSYNC="${ENGRAM_CLOUD_AUTOSYNC:-}"

if [ -n "$ENGRAM_SERVER" ] && [ -n "$ENGRAM_TOKEN" ]; then
    log "Engram Cloud env vars detected — wiring MCP server"
    ENGRAM_ENABLED=1
else
    warn "Engram Cloud env vars not set (ENGRAM_CLOUD_SERVER, ENGRAM_CLOUD_TOKEN)"
    warn "Engram MCP server WILL NOT be registered. Memory protocol stays inactive."
    warn "Set the vars and re-run installer to enable Engram."
    ENGRAM_ENABLED=0
fi

# Self-healing: if Engram is desired but the binary is missing (fresh install,
# previous run failed, user upgraded), auto-install BEFORE writing the MCP
# entry. Otherwise config.yaml would point at a non-existent command and
# Hermes would crash on startup.
if [ "$ENGRAM_ENABLED" -eq 1 ]; then
    if ! check_engram_binary; then
        warn "Engram binary unavailable — DISABLING Engram MCP wiring for this run."
        warn "Re-run installer once 'engram' is in PATH (Homebrew or releases tarball)."
        ENGRAM_ENABLED=0
    fi
fi

if [ ! -f "$CONFIG_FILE" ]; then
    log "Creating config.yaml..."
    cat > "$CONFIG_FILE" << 'YAML'
_config_version: 23
model:
  api_mode: chat_completions
  base_url: https://opencode.ai/zen/go/v1
  default: kimi-k2.6
  provider: opencode-go
delegation:
  child_timeout_seconds: 600
  inherit_mcp_toolsets: true
  max_concurrent_children: 3
  max_iterations: 50
  max_spawn_depth: 2
  model: deepseek-v4-pro
  orchestrator_enabled: true
  provider: opencode-go
agent:
  max_turns: 90
plugins:
  enabled:
  - cobalt-routing
memory:
  memory_enabled: true
display:
  show_reasoning: true
  streaming: true
  tool_progress: verbose
logging:
  level: VERBOSE
YAML
    log "config.yaml created"
fi

log "Merging cobalt + engram + markitdown settings into config.yaml (preserving your config)..."
ENGRAM_ENABLED="$ENGRAM_ENABLED" \
ENGRAM_SERVER="$ENGRAM_SERVER" \
ENGRAM_TOKEN="$ENGRAM_TOKEN" \
ENGRAM_AUTOSYNC="$ENGRAM_AUTOSYNC" \
MARKITDOWN_BIN="$MARKITDOWN_BIN" \
"$VENV_DIR/bin/python" - << 'PYTHON'
import os
import yaml
from pathlib import Path

config_path = Path.home() / ".hermes" / "config.yaml"
config = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}

# Plugin enabled
plugins = config.setdefault("plugins", {})
enabled = plugins.setdefault("enabled", [])
if "cobalt-routing" not in enabled:
    enabled.append("cobalt-routing")

# Model defaults
model = config.setdefault("model", {})
model.setdefault("default", "kimi-k2.6")
model.setdefault("provider", "opencode-go")
model.setdefault("base_url", "https://opencode.ai/zen/go/v1")
model.setdefault("api_mode", "chat_completions")

# Delegation defaults
deleg = config.setdefault("delegation", {})
deleg.setdefault("child_timeout_seconds", 600)
deleg.setdefault("max_concurrent_children", 3)
deleg.setdefault("max_iterations", 50)
deleg.setdefault("max_spawn_depth", 2)
deleg.setdefault("orchestrator_enabled", True)
deleg.setdefault("model", "deepseek-v4-pro")
deleg.setdefault("provider", "opencode-go")

# Memory: built-in only, no external provider (Engram surfaces via MCP)
memory = config.setdefault("memory", {})
memory.setdefault("memory_enabled", True)
# Strip legacy honcho provider so the single-external-provider slot stays free
if memory.get("provider") == "honcho":
    memory.pop("provider", None)

# Agent defaults
agent = config.setdefault("agent", {})
agent.setdefault("max_turns", 90)

# MCP servers (only the ones whose env vars / binaries are present)
mcp_servers = config.setdefault("mcp_servers", {})

# Engram MCP server wiring (only when env vars present)
if os.environ.get("ENGRAM_ENABLED") == "1":
    engram = mcp_servers.setdefault("engram", {})
    # `engram` binary exposes the MCP server via `engram mcp` subcommand
    engram["command"] = "engram"
    engram["args"] = ["mcp"]
    env = engram.setdefault("env", {})
    env["ENGRAM_CLOUD_SERVER"] = os.environ.get("ENGRAM_SERVER", "")
    env["ENGRAM_CLOUD_TOKEN"] = os.environ.get("ENGRAM_TOKEN", "")
    if os.environ.get("ENGRAM_AUTOSYNC"):
        env["ENGRAM_CLOUD_AUTOSYNC"] = os.environ["ENGRAM_AUTOSYNC"]

# markitdown MCP server wiring (only when the binary is in the venv)
markitdown_bin = os.environ.get("MARKITDOWN_BIN", "").strip()
if markitdown_bin:
    md = mcp_servers.setdefault("markitdown", {})
    md["command"] = markitdown_bin
    md["args"] = []

# Drop the mcp_servers section if it ended up empty so we don't leave a
# dangling key in user configs that never had MCP wiring.
if not mcp_servers:
    config.pop("mcp_servers", None)

config_path.write_text(
    yaml.dump(config, default_flow_style=False, allow_unicode=True, sort_keys=False),
    encoding="utf-8",
)
print("Config merged successfully")
PYTHON

# Clean up legacy honcho.json if present — Honcho is no longer used
LEGACY_HONCHO="$HERMES_HOME/honcho.json"
if [ -f "$LEGACY_HONCHO" ]; then
    mv "$LEGACY_HONCHO" "$LEGACY_HONCHO.bak"
    warn "Honcho is no longer used. Backed up $LEGACY_HONCHO -> $LEGACY_HONCHO.bak"
fi

log "Configuration complete"

# ============================================================================
header "Step 7/9: Skills Installation"
# ============================================================================

SKILLS_DIR="$HERMES_HOME/skills"
mkdir -p "$SKILLS_DIR"

SKILLS=(
    "skills-sh/wshobson/agents/prompt-engineering-patterns"
    "skills-sh/anthropics/skills/frontend-design"
    "skills-sh/dammyjay93/interface-design/interface-design"
    "skills-sh/wshobson/agents/e2e-testing-patterns"
    "skills-sh/wshobson/agents/error-handling-patterns"
    "skills-sh/wshobson/agents/postgresql-table-design"
    "skills-sh/gentleman-programming/sdd-agent-team/judgment-day"
    "skills-sh/gentleman-programming/sdd-agent-team/branch-pr"
    "skills-sh/gentleman-programming/sdd-agent-team/skill-creator"
    "skills-sh/thestark77/autosdd/knowledge-graph"
    # v0.8.0 additions — design / browser automation
    "skills-sh/microsoft/playwright-cli/playwright-cli"
    "skills-sh/pbakaus/impeccable/impeccable"
    "skills-sh/alchaincyf/huashu-design/huashu-design"
    "skills-sh/nextlevelbuilder/ui-ux-pro-max-skill/ui-ux-pro-max"
    "skills-sh/Leonxlnx/taste-skill/gpt-tasteskill"
)

SKILL_NAMES=(
    "prompt-engineering-patterns"
    "frontend-design"
    "interface-design"
    "e2e-testing-patterns"
    "error-handling-patterns"
    "postgresql-table-design"
    "judgment-day"
    "branch-pr"
    "skill-creator"
    "knowledge-graph"
    # v0.8.0 additions
    "playwright-cli"
    "impeccable"
    "huashu-design"
    "ui-ux-pro-max"
    "gpt-tasteskill"
)

log "Installing ${#SKILLS[@]} skills..."

HERMES_BIN="$HOME/.local/bin/hermes"
SKILLS_INSTALLED=0
SKILLS_FAILED=()

# Verify a skill is actually installed regardless of `hermes skills install`
# exit code (the CLI sometimes prints "Error: Could not fetch" but still
# returns 0 — checking the filesystem is the authoritative signal).
skill_is_installed() {
    local name="$1"
    [ -f "$SKILLS_DIR/$name/SKILL.md" ]
}

for i in "${!SKILLS[@]}"; do
    name="${SKILL_NAMES[$i]}"
    identifier="${SKILLS[$i]}"

    if skill_is_installed "$name"; then
        if [ "$IS_UPDATE" -eq 1 ]; then
            # Re-run install to pull latest; --force skips security re-confirm.
            # We don't fail the run if update doesn't go through; the existing
            # copy is still functional.
            if "$HERMES_BIN" skills install "$identifier" --force >/dev/null 2>&1 \
                && skill_is_installed "$name"; then
                log "  $name (updated)"
            else
                log "  $name (kept existing)"
            fi
            SKILLS_INSTALLED=$((SKILLS_INSTALLED + 1))
        else
            log "  $name (already installed)"
            SKILLS_INSTALLED=$((SKILLS_INSTALLED + 1))
        fi
        continue
    fi

    # Not present yet — attempt install. Tolerate the CLI's noisy "Error"
    # output; trust the post-install filesystem check.
    "$HERMES_BIN" skills install "$identifier" --force >/dev/null 2>&1 || true
    if skill_is_installed "$name"; then
        log "  $name (installed)"
        SKILLS_INSTALLED=$((SKILLS_INSTALLED + 1))
    else
        warn "  $name (failed — try: hermes skills install $identifier --force)"
        SKILLS_FAILED+=("$name")
    fi
done

if [ "${#SKILLS_FAILED[@]}" -gt 0 ]; then
    warn "$SKILLS_INSTALLED/${#SKILLS[@]} skills installed — missing: ${SKILLS_FAILED[*]}"
    warn "Re-run installer once upstream sources are reachable; only the missing skills will be retried."
else
    log "$SKILLS_INSTALLED/${#SKILLS[@]} skills installed"
fi

# ============================================================================
header "Step 8/9: Patch verify automation"
# ============================================================================

# engram binary check is handled in Step 6 (before MCP wiring) — no need to repeat.
setup_verify_cron

# ============================================================================
header "Step 9/9: Verification"
# ============================================================================

CHECKS=0
TOTAL=6

# Check 1: Hermes binary
if command -v hermes &>/dev/null || [ -x "$HERMES_BIN" ]; then
    log "✓ hermes binary accessible"
    CHECKS=$((CHECKS + 1))
else
    err "✗ hermes not in PATH"
fi

# Check 2: Plugin files
if [ -f "$PLUGIN_DIR/__init__.py" ] && [ -f "$PLUGIN_DIR/router.py" ]; then
    log "✓ cobalt-routing plugin installed"
    CHECKS=$((CHECKS + 1))
else
    err "✗ plugin files missing"
fi

# Check 3: Source patch
if [ -f "$PATCH_SCRIPT" ] && "$VENV_DIR/bin/python" "$PATCH_SCRIPT" verify 2>/dev/null; then
    log "✓ delegate_tool.py patch applied"
    CHECKS=$((CHECKS + 1))
else
    warn "△ source patch not verified (routing will use inference fallback)"
    CHECKS=$((CHECKS + 1))
fi

# Check 4: SOUL.md
if [ -f "$HERMES_HOME/SOUL.md" ]; then
    log "✓ SOUL.md deployed"
    CHECKS=$((CHECKS + 1))
else
    err "✗ SOUL.md missing"
fi

# Check 5: Config has plugin enabled
if grep -q "cobalt-routing" "$CONFIG_FILE" 2>/dev/null; then
    log "✓ Plugin enabled in config"
    CHECKS=$((CHECKS + 1))
else
    err "✗ Plugin not enabled in config"
fi

# Check 6: Version compatibility
FINAL_HERMES=$(read_hermes_version)
if version_gte "$FINAL_HERMES" "$HERMES_ERROR_FROM"; then
    err "✗ Hermes $FINAL_HERMES is incompatible"
elif version_gte "$FINAL_HERMES" "$HERMES_WARN_FROM"; then
    warn "△ Hermes $FINAL_HERMES is above tested version ($HERMES_TESTED_VERSION)"
    CHECKS=$((CHECKS + 1))
else
    log "✓ Hermes $FINAL_HERMES compatible (tested: $HERMES_TESTED_VERSION)"
    CHECKS=$((CHECKS + 1))
fi

echo ""
header "$([ "$IS_UPDATE" -eq 1 ] && echo 'Update' || echo 'Installation') Complete"

if [ "$CHECKS" -eq "$TOTAL" ]; then
    log "All checks passed ($CHECKS/$TOTAL)"
else
    warn "Some checks failed ($CHECKS/$TOTAL) — review warnings above"
fi

echo ""
echo -e "${CYAN}Next steps:${NC}"
if [ "$ENGRAM_ENABLED" -ne 1 ]; then
    echo "  1. Export Engram Cloud env vars and re-run installer:"
    echo "       export ENGRAM_CLOUD_SERVER=https://your-engram.host"
    echo "       export ENGRAM_CLOUD_TOKEN=your-token"
    echo "       export ENGRAM_CLOUD_AUTOSYNC=1   # optional"
    echo "     Then: bash install.sh"
    echo ""
fi
if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
    echo "  2. (Optional) Enable patch-drift Telegram alerts:"
    echo "       export TELEGRAM_BOT_TOKEN=your-bot-token"
    echo "       export TELEGRAM_CHAT_ID=your-chat-id"
    echo "     Then: bash install.sh"
    echo ""
fi
echo "  Start Hermes:"
echo "     hermes chat"
echo ""
echo "  Test cobalt-routing:"
echo '     Ask: "Necesito un script en Python que lea un archivo JSON y genere un reporte"'
echo "     Watch for: triage -> explore -> apply -> verify phases with model routing"
echo ""
echo -e "${GREEN}cobalt-agent v${COBALT_VERSION} $([ "$IS_UPDATE" -eq 1 ] && echo 'updated' || echo 'ready').${NC}"
